Movie1: {
  shape: circle
  label: "Movie 1"
}
Movie2: {
  shape: circle
  label: "Movie 2"
}
Movie3: {
  shape: circle
  label: "Movie 3"
}
Movie4: {
  shape: circle
  label: "Movie 4"
}
Actor1: {
  shape: circle
  label: "Actor 1"
}
Actor2: {
  shape: circle
  label: "Actor 2"
}
Actor3: {
  shape: circle
  label: "Actor 3"
}
Actor4: {
  shape: circle
  label: "Actor 4"
}
Actor5: {
  shape: circle
  label: "Actor 5"
}

Movie1 <-> Actor1: Credits
Movie1 <-> Actor2: Credits
Movie2 <-> Actor3: Credits
Movie2 <-> Actor1: Credits
Movie3 <-> Actor4: Credits
Movie1 <-> Actor4: Credits
Movie3 <-> Actor5: Credits
Movie2 <-> Actor5: Credits
Movie4 <-> Actor5: Credits
Movie4 <-> Actor1: Credits
