Actors: {
  shape: class
  Name: "string"
  ActorID: "int"
  Details: "json"
}

Movies: {
  shape: class
  Title: "string"
  MovieID: "int"
  Details: "json"
}

Credits: {
  shape: class
  CreditID: "string"
  details: "json"
}
